import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Geist_Mono, Arimo } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { GlobalNotification } from "@/components/shared/GlobalNotification";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const arimo = Arimo({
  variable: "--font-arimo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${plusJakarta.variable} ${geistMono.variable} ${arimo.variable} antialiased`}
      >
        <GlobalNotification />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
